### ISSUE TITLE
TypeScript support?

### ISSUE THREAD

**Issue by runtothedoor** [flyskywhy/react-native-gcanvas#39]
Any plans?

**Comment by flyskywhy** [comment]
No.

Can you tell me why you need TypeScript in @flyskywhy/react-native-gcanvas?

**Comment by flyskywhy** [comment]
I don't like restrict by type check when programing, so I prefer JS not TS, and that's why I'm not familiar to TS, so I guess maybe there is some option in TypeScript to ignore type checking on specific path e.g. `node_modules/@flyskywhy/react-native-gcanvas`, can you look for it and tell me the result?

**Comment by 3GOMESz** [comment]
This can be done in typescript with comment lines ignoring imports or react-native-gcanvas calls but by many people this can be seen as "not so mature library" for lacking of typings. I recommend you look into TypeScript, it's not complicated, but I can offer help to create a typing file (index.d.ts) 😄

**Comment by flyskywhy** [comment]
Thanks first 😝 

Is one typing file (index.d.ts) enough? Cause there is more files in `node_modules/@flyskywhy/react-native-gcanvas/pacakges/`

**Comment by 3GOMESz** [comment]
Yep, one file is enough haha

**Comment by McMelonTV** [comment]
bruh what lmao
