### ISSUE TITLE
TypeError: Cannot read property 'preloadImage' of null

### ISSUE THREAD

**Issue by muh-hamada** [flyskywhy/react-native-gcanvas#52]
Hi,

I get this error (`TypeError: Cannot read property 'preloadImage' of null`) while using GImage like below:
```js
const imageHttp = new GImage();

imageHttp.crossOrigin = true;

imageHttp.onload = () => {
  console.log('loaded')
};

imageHttp.src = imgSrc
```

I checked the source code and we set `GBridge = null`

https://github.com/flyskywhy/react-native-gcanvas/blob/7543f57e0c95d1cfac77bab7a8d2d775e05f0f17/packages/gcanvas/src/env/image.js#L11

**Comment by flyskywhy** [comment]
That' because `GImage.GBridge` will be `= bridge` by `enable()` in https://github.com/flyskywhy/react-native-gcanvas/blob/7543f57e0c95d1cfac77bab7a8d2d775e05f0f17/packages/gcanvas/src/index.js#L16

So you should using `const imageHttp = new GImage();` after `onCanvasCreate()` is called (means  `enable()` is called ref to https://github.com/flyskywhy/react-native-gcanvas/blob/7543f57e0c95d1cfac77bab7a8d2d775e05f0f17/components/GCanvasComponent.js#L159) just like what `READEM.md` described :stuck_out_tongue:

**Comment by muh-hamada** [comment]
Ok, thanks for the clarification 👍
